--!strict
--!optimize 2
--!nolint LocalShadow

local StyleSheet = Instance.new("StyleSheet")
StyleSheet:AddTag("64222081b2e42a1bc86bb93571b5db93")

local StyleRule_0 = Instance.new("StyleRule")
StyleRule_0.Selector = "TextInput"
StyleRule_0.Name = "TextInput"
StyleRule_0:SetProperties({
    ["BackgroundColor3"] = Color3.new(1, 0, 0),
})
StyleRule_0.Parent = StyleSheet

StyleSheet.Parent = script
return StyleSheet